---
engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
    - "**/*spec.rb"
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.js"
  - "**.rb"
